version: "3.7"
services:
  aphotos:
    build: .
    image: aphotos
    ports:
      - "7800:7800"
    volumes:
      - "./client:/usr/src/aicha.photos/client"
      - "./server:/usr/src/aicha.photos/server"
